# Generated by Django 5.1.4 on 2024-12-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeaLeaves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_name", models.CharField(max_length=120)),
                ("collected_weight", models.FloatField()),
                ("any_note", models.TextField(blank=True, null=True)),
                ("collected_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
