# Generated by Django 5.1.4 on 2024-12-22 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tealeaves",
            name="collected_weight",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tealeaves",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
