# Generated by Django 5.1.4 on 2024-12-30 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tealeaves",
            name="collectored_at",
            field=models.DateTimeField(auto_now_add=True, default=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tealeaves",
            name="collector_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="collector_name",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
