# Generated by Django 5.1.4 on 2024-12-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_tealeaves_collected_weight_alter_tealeaves_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tealeaves",
            name="collected_weight",
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
    ]
