# Generated by Django 5.1.4 on 2025-01-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_tealeaves_collector_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tealeaves',
            name='quality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
